### ISSUE TITLE
Create our system's logo and design color palette

### ISSUE THREAD

**Issue by PiCiU1221** [PiCiU1221/BookRider#10]

**Comment by jpie02** [comment]
![Image](https://github.com/user-attachments/assets/92446e33-8f6c-4563-8921-f001868d1a83)
![Image](https://github.com/user-attachments/assets/39f663db-5f8a-4924-870b-618d91c8a96a)
![Image](https://github.com/user-attachments/assets/81c4e2a1-9903-4dbc-8805-5274eb1320e0)
[color_palette_hex_codes.txt](https://github.com/user-attachments/files/17924944/color_palette_hex_codes.txt)
