### ISSUE TITLE
Create Project Timeline document

### ISSUE THREAD

**Issue by PiCiU1221** [PiCiU1221/BookRider#2]

**Comment by Naivezz** [comment]
[Create Project Timeline document.pdf](https://github.com/user-attachments/files/17807086/Create.Project.Timeline.document.pdf)

**Comment by Naivezz** [comment]
[Project Timeline document.pdf](https://github.com/user-attachments/files/17807117/Project.Timeline.document.pdf)

**Comment by PiCiU1221** [comment]
Looks good to me. I'll upload it to the repositories's wiki in a minute.

**Comment by PiCiU1221** [comment]
Uploaded in here: [Project Timeline](https://github.com/PiCiU1221/BookRider/wiki/Project-Timeline)
